# Generated by Django 5.0.4 on 2024-04-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='uid',
            new_name='uuid',
        ),
    ]
